### PR TITLE
Update glyph.csv

### PR DESCRIPTION
**Pull request by emgeka**
Added "refresh,mind,refresh,body," sequence.

### CODE REVIEW

**Comment by chibatching** [comment]
Could you provide a screenshot or official announcement of this sequence?

**Comment by emgeka** [comment]
I'll try taking a screenshot ASAP, however I've just recursed yesterday and will have to level up. 

For the time being here are two sources that reference the sequence: 

1. https://glyph.somerian.net/glyphs/refresh

(second from the top) 

2. https://www.reddit.com/r/Ingress/s/PLsNnX9FX9

**Comment by emgeka** [comment]
> Could you provide a screenshot or official announcement of this sequence?

Sorry for the delay. Here it is:

**Comment by emgeka** [comment]
> Could you provide a screenshot or official announcement of this sequence?

Sorry for the delay. Here it is:

**Comment by chibatching** [comment]
Thank you!

**Pull request merged**
